bg_default: &bg_default {stack: [{background: {color: 81A1C1ff}}, {underline: {size: 4, color: D8DEE9ff}}]}
bar:
  height: 20
  location: top
  font: Blex Mono Nerd Font Mono:pixelsize=13
  spacing: 2
  margin: 0
  layer: bottom
  foreground: eeeeeeff
  background: 2E3440dd

  left:
    - river:
        title: { string: {  margin: 5, text: "{title} ({layout}/({mode}))" } }
        anchors:
          - base: &river_base
              left-margin: 7
              right-margin: 10
              default: {string: {text: "{id}"}}
              conditions:
                id == 1: {string: {text: ""}}
                id == 2: {string: {text: ""}}
                id == 3: {string: {text: ""}}
                id == 4: {string: {text: ""}}
                id == 5: {string: {text: "󰙯"}}

        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              # state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 3, color: ea6962ff}}
  right:
    - network:
        poll-interval: 1000
        content:
          map:
            conditions:
              # name != "lo":
              #   string: {text: "{name}: {state} ({ssid})"}
              # name == "eth0":
              #   string: {text: "{name}: {state} ({carrier})"}
              name == wlan0:
                string: {text: "[{name}: {state} ({ssid}) {dl-speed:mb}/{ul-speed:mb}]"}
    - pulse:
        content:
          map:
            default:
              string: { text: "[{sink_percent}%]" }
            conditions:
              sink_muted:
                string: { text: "[{sink_percent}% muted]" }
    - backlight:
        name: amdgpu_bl1
        content:
          string: { text: "[backlight: {percent}%]"}
    - battery:
        name: BAT0
        content:
          string: { text: "[BAT: {capacity}% {estimate}]"}
    - clock:
        date-format: "%Y/%m/%d" 
        content:
           string: { text: "[{date} {time}]" }
