theme = "amberwood"

[editor]
line-number = "relative"
mouse = false
# shell = [ "nu", "-c" ]
bufferline = "multiple"

[editor.lsp]
display-inlay-hints = true

[editor.auto-pairs]
'(' = ')'
'[' = ']'
'{' = '}'
# '<' = '>'
'"' = '"'
'`' = '`'
"'" = "'"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[keys.insert]
up       = "no_op"
down     = "no_op"
left     = "no_op"
right    = "no_op"
pageup   = "no_op"
pagedown = "no_op"
home     = "no_op"
end      = "no_op"
